[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "fg8jwjQaTebokzZBE5YWxFeRGuSZeVv1LW7oF4PPiu9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/debian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
